/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_redknot_redeyeandroid_NativeMethod */

#ifndef _Included_com_redknot_redeyeandroid_NativeMethod
#define _Included_com_redknot_redeyeandroid_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_redknot_redeyeandroid_NativeMethod
 * Method:    Start
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_redknot_redeyeandroid_NativeMethod_Start
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_redknot_redeyeandroid_NativeMethod
 * Method:    Update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_redknot_redeyeandroid_NativeMethod_Update
  (JNIEnv *, jclass);

/*
 * Class:     com_redknot_redeyeandroid_NativeMethod
 * Method:    End
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_redknot_redeyeandroid_NativeMethod_End
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
